name: Fetch Flickr Photos

on:
  push:
    branches:
      - main  # eller den branch du använder för din GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch photos from Flickr
        run: |
          echo "const apiKey = '${{ secrets.FLICKR_API_KEY }}';" > api_key.js
          echo "console.log('API Key fetched successfully');" >> api_key.js

      - name: Deploy to GitHub Pages
        run: |
          # Här kan du lägga till steg för att deploya till GitHub Pages
